version: '3'
services:
  mysql:
    image: mariadb:10.5.9
    command: --max_allowed_packet=256M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always  
  litespeed:
    image: litespeedtech/litespeed:${LSWS_VERSION}-${PHP_VERSION}
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 7080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
  phpmyadmin:
    image: bitnami/phpmyadmin:5.0.2-debian-10-r72
    ports:
      - 8080:80
      - 8443:443
    environment:
        DATABASE_HOST: mysql
    restart: always    
